apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.userService.svcPort }}
      targetPort: {{ .Values.userService.containerPort }}
  selector:
    app: {{ .Values.userService.name }}