apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-fullstack-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: usersvc.backendgeeks.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "service.fullname" . }}
                port:
                  number: {{ .Values.userService.svcPort }}
    - host: productsvc.backendgeeks.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "product.fullname" . }}
                port:
                  number: {{ .Values.productService.svcPort }}