userService:
  name: user-service
  image: teten/myuserapp:0.3.0
  replicas: 1
  containerPort: 8081
  svcPort: 80

productService:
  name: product-service
  image: teten/myproduct:0.3.0
  replicas: 1
  containerPort: 8082
  svcPort: 80

ingress:
  enabled: true
  host: xyz.backendgeeks.com
  userPath: /users
  productPath: /products

namespace: golang-fullstack